// <auto-generated>
// Rewired Constants
// This list was generated on 2026/7/4 10:25:41
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        // Motion
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Motion", friendlyName = "move-x")]
        public const int move_x = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Motion", friendlyName = "move-y")]
        public const int move_y = 1;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Motion", friendlyName = "jump")]
        public const int jump = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Motion", friendlyName = "cam-x")]
        public const int cam_x = 3;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Motion", friendlyName = "cam-y")]
        public const int cam_y = 4;
        
    }
    public static partial class Category {
        public const int Default = 0;
        
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
            
        }
        public static partial class Keyboard {
            public const int Default = 0;
            
        }
        public static partial class Mouse {
            public const int Default = 0;
            
        }
        public static partial class CustomController {
            public const int Default = 0;
            
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
        
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
